In [28]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv('dataset.csv')

In [30]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [31]:
for i in df.columns:
    print(df[i].value_counts)

<bound method IndexOpsMixin.value_counts of 0       7590-VHVEG
1       5575-GNVDE
2       3668-QPYBK
3       7795-CFOCW
4       9237-HQITU
           ...
7027    6840-RESVB
7028    2234-XADUH
7029    4801-JZAZL
7030    8361-LTMKD
7031    3186-AJIEK
Name: customerID, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       Female
1         Male
2         Male
3         Male
4       Female
         ...
7027      Male
7028    Female
7029    Female
7030      Male
7031      Male
Name: gender, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       0
1       0
2       0
3       0
4       0
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: SeniorCitizen, Length: 7032, dtype: int64>
<bound method IndexOpsMixin.value_counts of 0       Yes
1        No
2        No
3        No
4        No
       ...
7027    Yes
7028    Yes
7029    Yes
7030    Yes
7031     No
Name: Partner, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        No
1        No
2        No
3        No
4        No
       ...
7027    Yes
7028    Yes
7029    Yes
7030     No
7031     No
Name: Dependents, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        1
1       34
2        2
3       45
4        2
        ..
7027    24
7028    72
7029    11
7030     4
7031    66
Name: tenure, Length: 7032, dtype: int64>
<bound method IndexOpsMixin.value_counts of 0        No
1       Yes
2       Yes
3        No
4       Yes
       ...
7027    Yes
7028    Yes
7029     No
7030    Yes
7031    Yes
Name: PhoneService, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       No phone service
1                     No
2                     No
3       No phone service
4                     No
              ...
7027                 Yes
7028                 Yes
7029    No phone service
7030                 Yes
7031                  No
Name: MultipleLines, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0               DSL
1               DSL
2               DSL
3               DSL
4       Fiber optic
           ...
7027            DSL
7028    Fiber optic
7029            DSL
7030    Fiber optic
7031    Fiber optic
Name: InternetService, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        No
1       Yes
2       Yes
3       Yes
4        No
       ...
7027    Yes
7028     No
7029    Yes
7030     No
7031    Yes
Name: OnlineSecurity, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       Yes
1        No
2       Yes
3        No
4        No
       ...
7027     No
7028    Yes
7029     No
7030     No
7031     No
Name: OnlineBackup, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        No
1       Yes
2        No
3       Yes
4        No
       ...
7027    Yes
7028    Yes
7029     No
7030     No
7031    Yes
Name: DeviceProtection, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        No
1        No
2        No
3       Yes
4        No
       ...
7027    Yes
7028     No
7029     No
7030     No
7031    Yes
Name: TechSupport, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        No
1        No
2        No
3        No
4        No
       ...
7027    Yes
7028    Yes
7029     No
7030     No
7031    Yes
Name: StreamingTV, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        No
1        No
2        No
3        No
4        No
       ...
7027    Yes
7028    Yes
7029     No
7030     No
7031    Yes
Name: StreamingMovies, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       Month-to-month
1             One year
2       Month-to-month
3             One year
4       Month-to-month
             ...
7027          One year
7028          One year
7029    Month-to-month
7030    Month-to-month
7031          Two year
Name: Contract, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       Yes
1        No
2       Yes
3        No
4       Yes
       ...
7027    Yes
7028    Yes
7029    Yes
7030    Yes
7031    Yes
Name: PaperlessBilling, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0                Electronic check
1                    Mailed check
2                    Mailed check
3       Bank transfer (automatic)
4                Electronic check
                  ...
7027                 Mailed check
7028      Credit card (automatic)
7029             Electronic check
7030                 Mailed check
7031    Bank transfer (automatic)
Name: PaymentMethod, Length: 7032, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...
7027     84.80
7028    103.20
7029     29.60
7030     74.40
7031    105.65
Name: MonthlyCharges, Length: 7032, dtype: float64>
<bound method IndexOpsMixin.value_counts of 0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7027    1990.50
7028    7362.90
7029     346.45
7030     306.60
7031    6844.50
Name: TotalCharges, Length: 7032, dtype: float64>
<bound method IndexOpsMixin.value_counts of 0        No
1        No
2       Yes
3        No
4       Yes
       ...
7027     No
7028     No
7029     No
7030    Yes
7031     No
Name: Churn, Length: 7032, dtype: object>

In [32]:
mapping = { "gender" : { "Male" : 0, "Female" : 1 },
                "Partner" : { "Yes" : 0, "No" : 1},
                "Dependents" : { "Yes" : 0, "No" : 1},
                "PhoneService" : { "Yes" : 0, "No" : 1},
                "PaperlessBilling" : { "Yes" : 0, "No" : 1},
                "Churn" : { "Yes" : 0, "No" : 1},
                "MultipleLines" : { "Yes" : 0, "No" : 1, "No phone service" : 2},
                "InternetService" : { "DSL" : 0, "Fiber optic" : 1, "No" : 2},
                "Contract" : { "Month-to-month" : 0, "One year" : 1, "Two year" : 2},
                "PaymentMethod" : { "Electronic check" : 0, "Mailed check" : 1, "Bank transfer (automatic)" : 2, "Credit card (automatic)" : 3},
                "StreamingTV" : { "Yes" : 0, "No" : 1, "No internet service" : 2},
                "StreamingMovies" : { "Yes" : 0, "No" : 1, "No internet service" : 2},
                "TechSupport" : { "Yes" : 0, "No" : 1, "No internet service" : 2},
                "OnlineSecurity" : { "Yes" : 0, "No" : 1, "No internet service" : 2},
                "OnlineBackup" : { "Yes" : 0, "No" : 1, "No internet service" : 2},
                "DeviceProtection" : { "Yes" : 0, "No" : 1, "No internet service" : 2},
                }

In [33]:
df = df.replace(mapping)

In [34]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,0,0,1,1,1,2,0,1,...,1,1,1,1,0,0,0,29.85,29.85,1
1,5575-GNVDE,0,0,1,1,34,0,1,0,0,...,0,1,1,1,1,1,1,56.95,1889.50,1
2,3668-QPYBK,0,0,1,1,2,0,1,0,0,...,1,1,1,1,0,0,1,53.85,108.15,0
3,7795-CFOCW,0,0,1,1,45,1,2,0,0,...,0,0,1,1,1,1,2,42.30,1840.75,1
4,9237-HQITU,1,0,1,1,2,0,1,1,1,...,1,1,1,1,0,0,0,70.70,151.65,0

In [35]:
df.to_csv('cleaned_dataset.csv')

In [36]:
import json

In [37]:
with open('mapping.json','w') as f:
    json.dump(mapping,f)